# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys, res


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(634, 565)
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(10)
        font.setUnderline(False)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(30, 20, 551, 501))
        self.widget.setStyleSheet("QPushButton#pushbutton{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushbutton-hover{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(90, 11, 50, 200));\n"
"}\n"
"\n"
"QPushButton#pushbutton-pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,11,250);\n"
"}\n"
"\n"
"QPushButton#pushbutton_2{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(85, 81, 84, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushbutton_2-hover{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(90, 11, 50, 200));\n"
"}\n"
"\n"
"QPushButton#pushbutton_2-pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,11,250);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 461))
        self.label.setStyleSheet("border-image: url(:/pic/background/bbn.png);\n"
"border-top-left-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 280, 461))
        self.label_2.setStyleSheet("background-colour:rgba(0,0,0,80);\n"
"border-top-left-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 240, 461))
        self.label_3.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(360, 70, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(0,0,0,200)")
        self.label_4.setObjectName("label_4")
        self.username = QtWidgets.QLineEdit(parent=self.widget)
        self.username.setGeometry(QtCore.QRect(310, 150, 190, 40))
        self.username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setGeometry(QtCore.QRect(310, 210, 190, 40))
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.login_button = QtWidgets.QPushButton(parent=self.widget)
        self.login_button.setGeometry(QtCore.QRect(310, 295, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(310, 350, 191, 16))
        self.label_5.setStyleSheet("color:rgba(0,0,0,210);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(310, 390, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.linkedin_button = QtWidgets.QPushButton(parent=self.widget)
        self.linkedin_button.setGeometry(QtCore.QRect(310, 420, 31, 31))
        self.linkedin_button.setStyleSheet("border-image: url(:/pic/icons/linkedin.png);")
        self.linkedin_button.setText("")
        self.linkedin_button.setObjectName("linkedin_button")
        self.fb_button = QtWidgets.QPushButton(parent=self.widget)
        self.fb_button.setGeometry(QtCore.QRect(350, 420, 31, 31))
        self.fb_button.setStyleSheet("border-image: url(:/pic/icons/facebook.png);")
        self.fb_button.setText("")
        self.fb_button.setObjectName("fb_button")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(40, 70, 251, 141))
        self.label_7.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 90, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Log In"))
        self.username.setPlaceholderText(_translate("Form", " Username"))
        self.password.setPlaceholderText(_translate("Form", " Password"))
        self.login_button.setText(_translate("Form", "Log In"))
        self.label_5.setText(_translate("Form", "Forgot your username or password?"))
        self.label_6.setText(_translate("Form", "Contact Admin "))
        self.label_8.setText(_translate("Form", "Blood Donor \n"
"Managment System"))
